In [1]:
import sklearn as sk
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.externals import joblib

C:\Users\shkatta\python_anaconda\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [14]:
data=pd.read_csv('C:\\Users\\shkatta\\Desktop\\AI\\csv files\\red.csv')

In [15]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [18]:
data.shape

(1599, 12)

In [25]:
y = data.quality
X = data.drop('quality', axis=1)


In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=123, 
                                                    stratify=y)
X_train.shape


(1279, 11)

In [39]:

scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)



In [44]:
print(X_train_scaled.mean(axis=0))

[ 1.16664562e-16 -3.05550043e-17 -8.47206937e-17 -2.22218213e-17
  1.94440936e-17 -6.38877362e-17 -4.16659149e-18 -1.20753377e-13
 -8.70817622e-16 -4.08325966e-16 -1.17220107e-15]


In [41]:
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled.mean(axis=0)
 

array([ 0.02776704,  0.02592492, -0.03078587, -0.03137977, -0.00471876,
       -0.04413827, -0.02414174, -0.00293273, -0.00467444, -0.10894663,
        0.01043391])

In [45]:
X_test_scaled.std(axis=0)

array([1.02160495, 1.00135689, 0.97456598, 0.91099054, 0.86716698,
       0.94193125, 1.03673213, 1.03145119, 0.95734849, 0.83829505,
       1.0286218 ])

In [46]:
pipeline = make_pipeline(preprocessing.StandardScaler(), 
                         RandomForestRegressor(n_estimators=100))

In [47]:

pipeline.get_params()

{'memory': None,
 'steps': [('standardscaler',
   StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('randomforestregressor',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                         max_features='auto', max_leaf_nodes=None,
                         min_impurity_decrease=0.0, min_impurity_split=None,
                         min_samples_leaf=1, min_samples_split=2,
                         min_weight_fraction_leaf=0.0, n_estimators=100,
                         n_jobs=None, oob_score=False, random_state=None,
                         verbose=0, warm_start=False))],
 'verbose': False,
 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True),
 'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                       max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1,

In [48]:
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [49]:
clf = GridSearchCV(pipeline, hyperparameters, cv=10)
 

In [50]:
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split

In [51]:
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split

In [52]:
pred = clf.predict(X_test)

In [53]:
r2_score(y_test, pred)

0.46854458502330654

In [54]:
mean_squared_error(y_test, pred)

0.3429340625

In [55]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [57]:
classifier=Sequential([Dense(6,input_shape=(11,),activation='relu'),
                      Dense(1,activation='tanh')])
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


In [58]:
classifier.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

In [60]:
classifier.fit(X_train,y_train,batch_size=10,epochs=400)

Epoch 1/400
1279/1279 [==============================] - 1s 665us/step - loss: 25.6378 - accuracy: 0.0000e+00
Epoch 2/400
1279/1279 [==============================] - 0s 95us/step - loss: 22.2177 - accuracy: 0.0000e+00
Epoch 3/400
1279/1279 [==============================] - 0s 84us/step - loss: 22.1812 - accuracy: 0.0000e+00
Epoch 4/400
1279/1279 [==============================] - 0s 108us/step - loss: 22.1687 - accuracy: 0.0000e+00
Epoch 5/400
1279/1279 [==============================] - 0s 97us/step - loss: 22.1607 - accuracy: 0.0000e+00
Epoch 6/400
1279/1279 [==============================] - 0s 97us/step - loss: 22.1577 - accuracy: 0.0000e+00
Epoch 7/400
1279/1279 [==============================] - 0s 84us/step - loss: 22.1573 - accuracy: 0.0000e+00
Epoch 8/400
1279/1279 [==============================] - 0s 83us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 9/400
1279/1279 [==============================] - 0s 101us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 10/400
127

1279/1279 [==============================] - 0s 80us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 147/400
1279/1279 [==============================] - 0s 78us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 148/400
1279/1279 [==============================] - 0s 76us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 149/400
1279/1279 [==============================] - 0s 76us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 150/400
1279/1279 [==============================] - 0s 77us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 151/400
1279/1279 [==============================] - 0s 77us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 152/400
1279/1279 [==============================] - 0s 76us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 153/400
1279/1279 [==============================] - 0s 76us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 154/400
1279/1279 [==============================] - 0s 78us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 155/400
1

1279/1279 [==============================] - 0s 83us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 293/400
1279/1279 [==============================] - 0s 82us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 294/400
1279/1279 [==============================] - 0s 79us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 295/400
1279/1279 [==============================] - 0s 77us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 296/400
1279/1279 [==============================] - 0s 78us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 297/400
1279/1279 [==============================] - 0s 78us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 298/400
1279/1279 [==============================] - 0s 76us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 299/400
1279/1279 [==============================] - 0s 79us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 300/400
1279/1279 [==============================] - 0s 77us/step - loss: 22.1572 - accuracy: 0.0000e+00
Epoch 301/400
1